blank_issues_enabled: false
contact_links:
  - name: ğŸ” Security Vulnerabilities
    url: https://github.com/n1netails/security
    about: |
      Please DO NOT report vulnerabilities publicly.
      Use our responsible disclosure process.